# Generated by Django 4.2.4 on 2023-09-20 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kvrachu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
        migrations.CreateModel(
            name='Zapis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор', primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Дата записи')),
                ('doctor', models.ForeignKey(help_text='Пациент', on_delete=django.db.models.deletion.PROTECT, to='kvrachu.doctor')),
                ('patient', models.ForeignKey(help_text='Пациент', on_delete=django.db.models.deletion.PROTECT, to='kvrachu.patient')),
            ],
        ),
    ]
