# Generated by Django 4.2.4 on 2023-09-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvrachu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='login',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
    ]
