# Generated by Django 4.2.4 on 2023-10-04 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvrachu', '0002_rename_patients_patient_zapis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartabolezni',
            name='patient',
            field=models.ForeignKey(help_text='Пациент', on_delete=django.db.models.deletion.PROTECT, related_name='kartabolezni', to='kvrachu.patient'),
        ),
    ]
