# Generated by Django 4.2.4 on 2023-09-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvrachu', '0002_remove_doctor_login_remove_doctor_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='sunday',
            new_name='Воскресенье',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='tuesday',
            new_name='Вторник',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='monday',
            new_name='Понедельник',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='friday',
            new_name='Пятница',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='wednesday',
            new_name='Среда',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='saturday',
            new_name='Суббота',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='thursday',
            new_name='Четверг',
        ),
    ]
