# Generated by Django 4.2.4 on 2023-09-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvrachu', '0003_rename_sunday_timetable_воскресенье_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='Пятница',
            new_name='friday',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='Понедельник',
            new_name='monday',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='Суббота',
            new_name='saturday',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='Воскресенье',
            new_name='sunday',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='Четверг',
            new_name='thursday',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='Вторник',
            new_name='tuesday',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='Среда',
            new_name='wednesday',
        ),
    ]
